"""work with existing data

Revision ID: 8185c8d9dafb
Revises: e8968b8e2855
Create Date: 2021-06-02 05:51:26.203416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8185c8d9dafb'
down_revision = 'e8968b8e2855'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    """ Modify from False to True, so we can add a column that applies to our
    existing data successfully. """
    # op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=False))
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))

    """ update the existing records that don't yet have a 
    completed column with SQL """
    op.execute('UPDATE todos SET completed = False WHERE completed is NULL;')

    """ update the column on todos """
    op.alter_column('todos', 'completed', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
