"""add completed column

Revision ID: a68fdf8c772b
Revises: 526d29751328
Create Date: 2021-07-23 02:00:36.364473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a68fdf8c772b'
down_revision = '526d29751328'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=False))


    """ Modify from False to True, so we can add a column that applies to our
    existing data successfully. """
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))

    """ add the following two lines """
    # update the existing recoreds that don't yet have a completed column with SQL
    op.execute('UPDATE todos SET completed = False WHERE completed IS NULL;')
     # update the column on todos
    op.alter_column('todos', 'completed', nullable=False)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
