"""create todolist model

Revision ID: aaa2f3a607b6
Revises: a68fdf8c772b
Create Date: 2021-07-24 11:12:04.737502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaa2f3a607b6'
down_revision = 'a68fdf8c772b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todolists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    # op.add_column('todos', sa.Column('list_id', sa.Integer(), nullable=False))
    op.add_column('todos', sa.Column('list_id', sa.Integer(), nullable=True))
    
    op.create_foreign_key(None, 'todos', 'todolists', ['list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'list_id')
    op.drop_table('todolists')
    # ### end Alembic commands ###
